# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cardinality', models.IntegerField()),
                ('description', models.CharField(max_length=512)),
                ('value', models.IntegerField(blank=True)),
                ('gamificar', models.BooleanField(default=True)),
                ('num_questions_gami', models.IntegerField()),
            ],
            options={
                'ordering': ['cardinality'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cardinality', models.IntegerField()),
                ('description', models.CharField(max_length=512)),
                ('value', models.IntegerField(blank=True)),
                ('gamificar', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='subject.Subject')),
            ],
            options={
                'ordering': ['cardinality', 'name'],
            },
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='topic.Topic'),
        ),
    ]
