# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_generated', models.PositiveIntegerField(default=0)),
                ('num_answered', models.PositiveIntegerField(default=0)),
                ('num_successful', models.PositiveIntegerField(default=0)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='question.Question')),
            ],
        ),
    ]
