# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_testdone_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdone',
            name='score_won',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testdone',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testsdone', to='test.Test'),
        ),
    ]
