# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='next_level',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prev_level',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
