# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre de la asignatura')),
                ('description', models.CharField(max_length=512, verbose_name='Breve descripción, máximo 512 caracteres')),
                ('category', models.CharField(max_length=75, verbose_name='Categoría')),
                ('test_opt', models.BooleanField(verbose_name='Examen final directo')),
                ('capacity', models.IntegerField(null=True, verbose_name='Nº máx. alumnos')),
                ('image', s3direct.fields.S3DirectField(blank=True, null=True, verbose_name='Imagen de la asignatura')),
                ('created_on', models.DateTimeField(blank=True)),
                ('students', smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='student', chained_model_field='user', related_name='my_subjects', to='user.UserProfile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='user.UserProfile')),
            ],
            options={
                'permissions': (('view_subject', 'View detail Subject'), ('register_subject', 'Student registers of subject'), ('unregister_subject', 'Student unregisters of subject')),
            },
        ),
    ]
