# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=150)),
                ('image', s3direct.fields.S3DirectField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(0, 'Una respuesta válida'), (1, 'Varias respuestas válidas')], default=0)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='topic.Subtopic')),
            ],
            options={
                'ordering': ['statement'],
            },
        ),
    ]
